apiVersion: apps/v1
kind: Deployment
metadata:
  name: auction
  namespace: ecommerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auction
  template:
    metadata:
      labels:
        app: auction
    spec:
      containers:
        - name: auction
          image: capstone-ecr/auction:latest
          ports:
            - containerPort: 5003
          envFrom:
            - secretRef:
                name: db-creds
            - configMapRef:
                name: app-config
