apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
  namespace: ecommerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
        - name: products
          image: <YOUR_ECR_REPO>/products:latest
          ports:
            - containerPort: 5001
          envFrom:
            - secretRef:
                name: db-creds
            - configMapRef:
                name: app-config
