---
apiVersion: v1
kind: Service
metadata:
  name: users-svc
  namespace: ecommerce
spec:
  selector:
    app: users
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: products-svc
  namespace: ecommerce
spec:
  selector:
    app: products
  ports:
    - port: 5001
      targetPort: 5001
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: cart-svc
  namespace: ecommerce
spec:
  selector:
    app: cart
  ports:
    - port: 5002
      targetPort: 5002
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: auction-svc
  namespace: ecommerce
spec:
  selector:
    app: auction
  ports:
    - port: 5003
      targetPort: 5003
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: ecommerce
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
